<?php

$dspaceDefaults = require __DIR__.'/defaults/dspace.php';

$contentPages = [
    'introduction',
    'films',
    'themes',
    'resources',
    'contact',
    'goldwag',
    'hirshow',
    'lindey',
    'sim',
    'wuga',
    'antisemitism',
    'arts',
    'culture',
    'easterneurope',
    'family',
    'food',
    'gorbals',
    'greatmigration',
    'history',
    'holocaust',
    'kindertransport',
    'languages',
    'music',
    'nazigermany',
    'religion',
    'synagoguemusic',
    'welfare',
];

return array_merge($dspaceDefaults, [
    'appname' => 'pointsofarrival',
    'fullname' => 'Points Of Arrival',
    'theme' => 'pointsofarrival',
    'url_prefix' => 'pointsofarrival',

    'adminemail' => 'lddt@mlist.is.ed.ac.uk',

    'container_id' => env('POINTSOFARRIVAL_CONTAINER_ID', 'bac433ed-36a9-4660-b49c-49d3fd0bed2c'),

    'oaipmhcollection' => 'hdl_10683_14558',

    'ga_code' => env('POINTSOFARRIVAL_GA_CODE', ''),

    'show_facets' => false,
    'homepage_fullwidth' => true,
    'homepage_recentitems' => false,
    'homepage_randomitems' => false,

    'content_pages' => $contentPages,

    'field_mappings' => [
        'Title' => 'dc.title.en',
        'Alternative Title' => 'dc.title.alternative.en',
        'Maker' => 'dc.contributor.author.en',
        'Author' => 'dc.contributor.author.en',
        'Country' => 'dc.coverage.spatialcountry.en',
        'City' => 'dc.coveragespatialcity.en',
        'Subject' => 'dc.subject.en',
        'Instrument' => 'dc.type.en',
        'Abstract' => 'dc.description.abstract.en',
        'Date' => 'dc.date.created',
        'Bitstream' => 'dc.format.original.en',
        'Thumbnail' => 'dc.format.thumbnail.en',
        'Place Made' => 'dc.coverage.spatial.en',
        'Date Made' => 'dc.coverage.temporal.en',
        'Period' => 'dc.coverage.temporalperiod.en',
        'Accession Number' => 'dc.identifier.en',
        'Technical Description' => 'dc.description.en',
        'Other Information' => 'dc.description.usage.en',
        'Collection' => 'dc.relation.ispartof.en',
        'Notes' => 'dc.description.cataloguernotes',
        'Measurements' => 'dc.format.extent.en',
        'Signature Date' => 'dc.format.signature.en',
        'Inscription' => 'dc.format.inscription.en',
        'Rights Holder' => 'dc.rights.holder.en',
        'Instrument Family' => 'dc.type.family.en',
        'Genus' => 'dc.type.genus.en',
        'Provenance' => 'dc.provenance.en',
        'Decorations' => 'dc.description.decoration.en',
        'Link' => 'dc.identifier.uri.en',
        'Maker Biography' => 'dc.contributor.authorbio.en',
        'Associated Musician Name' => 'dc.contributor.assocfull.en',
        'Associated Musician' => 'dc.contributor.assoc.en',
        'Piccolo Description' => 'dc.description.piccolo.en',
        'Short Description' => 'dc.description.level1.en',
        'Description' => 'dc.description.level2.en',
        'Associated Musician Biography' => 'dc.contributor.assocbio.en',
        'Instrument Type' => 'dc.type.desc.en',
        'Instrument Type History' => 'dc.type.history.en',
        'ImageURI' => 'dc.identifier.imageUri',
        'Rights Statement' => 'dc.rights.en',
        'Case' => 'dc.coverage.spatialcase.en',
        'Gallery' => 'dc.coverage.spatialgallery.en',
        'Maker Name' => 'dc.contributor.authorfull.en',
        'Hornbostel Sachs Classification' => 'dc.subject.classification.en',
        'Grouping' => 'dc.coverage.spatiallogical.en',
        'Specific Type' => 'dc.type.specific.en',
    ],

    'recorddisplay' => [
        'Title',
        'Alternative Title',
        'Instrument',
        'Instrument Family',
        'Maker',
        'Subject',
        'Place Made',
        'Date Made',
        'Inscription',
        'Author',
        'Country',
        'City',
        'Abstract',
        'Date',
        'Period',
        'Accession Number',
        'Technical Description',
        'Other Information',
        'Collection',
        'Notes',
        'Rights Holder',
        'Genus',
        'Provenance',
        'Decorations',
        'Maker Biography',
        'Associated Musician Full',
        'Associated Musician',
        'Piccolo Description',
        'Short Description',
        'Description',
        'Associated Musician Biography',
        'Instrument Type',
        'Instrument Type History',
    ],

    'filters' => [
        'Instrument' => 'type_filter',
        'Maker' => 'author_filter',
        'Place Made' => 'place_filter',
        'Gallery' => 'gallery_filter',
    ],

    'searchresult_display' => [
        'Title',
        'Instrument',
        'Maker',
        'Subject',
        'Abstract',
        'Bitstream',
        'Thumbnail',
    ],

    'search_fields' => [
        'Title' => 'dc.title',
        'Type' => 'dc.type',
        'Maker' => 'dc.contributor.author',
        'Place Made' => 'dc.coverage.spatial',
        'Accession Number' => 'dc.identifier.en',
    ],

    'related_fields' => [
        'Instrument' => 'dc.type.en',
    ],
    'related_number' => 6,

    'sort_fields' => [
        'Maker' => 'dc.contributor.author_sort',
        'Title' => 'dc.title_sort',
    ],
    'default_sort' => 'dc.title_sort+asc',

    'meta_fields' => [
        'Title',
        'Alternative Title',
        'Maker',
        'Subject',
        'Type',
    ],

    'feed_fields' => [
        'Title' => 'Title',
        'Author' => 'Author',
        'Maker' => 'Maker',
        'Subject' => 'Subject',
        'Country' => 'Country',
        'Description' => 'Abstract',
        'Date' => 'Date',
    ],

    'highlight_fields' => 'dc.title.en,dc.contributor.author,dc.subject.en,lido.country.en,dc.description.en,dc.relation.ispartof.en',

    'results_per_page' => 20,
]);
